name: Build LaTeX document

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: manuscript.tex
      - name: Upload PDF file to Releaser
        uses: softprops/action-gh-release@v2
        with:
          files: manuscript.pdf
